# Generated by Django 4.1.7 on 2023-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['slug'], 'verbose_name': 'Tâche'},
        ),
    ]
